services:
  bbdd:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_HOST_AUTH_METHOD=trust

    # volumes:
      # -archivosBBDD:containerPath:ro      
  admin:
    image: dpage/pgadmin4	
    ports:
      - 443
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    # volumes:
      # - archivosPGADMIN:containerPath:ro