"""quitamos el booleano

Revision ID: fc05ecbff3d2
Revises: f9986ebb0ad6
Create Date: 2022-09-05 16:43:17.681407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc05ecbff3d2'
down_revision = 'f9986ebb0ad6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productos', 'estaActivado')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('estaActivado', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
